export type Product = {
  slug: string
  name: string
  price: number // em reais
  oldPrice?: number
  color: string
  category: 'Classic' | 'Legendary' | 'Shiny' | 'Limited'
  img: string
  images: string[]
  description: string
  details: string[]
  specs: { label: string; value: string }[]
  stock: number
  rating: number
  reviews: number
  badges: string[]
  height: string // ex: "22cm"
}

export const catalog: Product[] = [
  {
    slug: 'pikachu',
    name: 'Pikachu',
    price: 45,
    color: '#00f3ff',
    category: 'Classic',
    img: 'https://images.unsplash.com/photo-1613771404721-1f92d799e49f?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1613771404721-1f92d799e49f?q=80&w=600',
      'https://images.unsplash.com/photo-1594736223565-3544c039a36d?q=80&w=600',
      'https://images.unsplash.com/photo-1544273677-c433136021d4?q=80&w=600',
    ],
    description: 'O Pokémon mais icônico do mundo em resina 8K de alta qualidade. Detalhes elétricos com acabamento neon que brilha sob luz UV.',
    details: [
      'Escultura digital original otimizada para impressão 3D',
      'Acabamento manual para remoção de suportes',
      'Opção de primer cinza para pintura personalizada',
      'Base temática inclusa no design',
    ],
    specs: [
      { label: 'Material', value: 'Resina Premium Tough' },
      { label: 'Dimensões', value: '12cm x 10cm x 8cm' },
      { label: 'Escala', value: '1:8' },
      { label: 'Tempo de Impressão', value: '8 Horas' },
    ],
    stock: 15,
    rating: 5,
    reviews: 32,
    badges: ['Classic', 'Best Seller'],
    height: '12cm',
  },
  {
    slug: 'gyarados',
    name: 'Gyarados',
    price: 120,
    oldPrice: 150,
    color: '#ff00ff',
    category: 'Legendary',
    img: 'https://images.unsplash.com/photo-1559124568-d5a0f7da1ec5?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1559124568-d5a0f7da1ec5?q=80&w=600',
      'https://images.unsplash.com/photo-1613771404721-1f92d799e49f?q=80&w=600',
    ],
    description: 'O dragão aquático em toda sua fúria. Escultura de grande porte com escamas individuais impressas em resina ultra-resistente.',
    details: [
      'Escamas individuais com detalhamento extremo',
      'Estrutura articulada nas nadadeiras',
      'Base de água simulada inclusa',
      'Pintura opcional sob encomenda',
    ],
    specs: [
      { label: 'Material', value: 'Resina ABS-Like' },
      { label: 'Dimensões', value: '35cm x 20cm x 15cm' },
      { label: 'Escala', value: '1:6' },
      { label: 'Tempo de Impressão', value: '28 Horas' },
    ],
    stock: 5,
    rating: 5,
    reviews: 18,
    badges: ['Legendary', 'Grande Porte'],
    height: '35cm',
  },
  {
    slug: 'alakazam',
    name: 'Alakazam',
    price: 85,
    color: '#00ff00',
    category: 'Classic',
    img: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=600',
      'https://images.unsplash.com/photo-1594736223565-3544c039a36d?q=80&w=600',
    ],
    description: 'O mestre psíquico com suas colheres. Impressão de alta precisão capturando cada detalhe da pose de batalha.',
    details: [
      'Colheres impressas em peça separada e montadas',
      'Pose de batalha dinâmica',
      'Base flutuante inclusa',
    ],
    specs: [
      { label: 'Material', value: 'Resina Premium Tough' },
      { label: 'Dimensões', value: '18cm x 12cm x 10cm' },
      { label: 'Escala', value: '1:8' },
      { label: 'Tempo de Impressão', value: '14 Horas' },
    ],
    stock: 8,
    rating: 4,
    reviews: 11,
    badges: ['Classic'],
    height: '18cm',
  },
  {
    slug: 'gengar',
    name: 'Gengar',
    price: 65,
    color: '#00f3ff',
    category: 'Classic',
    img: 'https://images.unsplash.com/photo-1594736223565-3544c039a36d?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1594736223565-3544c039a36d?q=80&w=600',
      'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=600',
    ],
    description: 'O fantasma sorridente da primeira geração. Detalhes dos dentes e olhos impressionantes na resina transparente roxa.',
    details: [
      'Olhos em resina translúcida roxa',
      'Sombra base inclusa',
      'Acabamento fosco para efeito fantasmagórico',
    ],
    specs: [
      { label: 'Material', value: 'Resina Translúcida' },
      { label: 'Dimensões', value: '15cm x 14cm x 10cm' },
      { label: 'Escala', value: '1:8' },
      { label: 'Tempo de Impressão', value: '10 Horas' },
    ],
    stock: 12,
    rating: 5,
    reviews: 27,
    badges: ['Classic', 'Popular'],
    height: '15cm',
  },
  {
    slug: 'machamp',
    name: 'Machamp',
    price: 95,
    color: '#ff00ff',
    category: 'Classic',
    img: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?q=80&w=600',
    ],
    description: 'Quatro braços, um campeão. A musculatura em detalhe 8K é impressionante — cada fibra muscular visível.',
    details: [
      'Quatro braços montados individualmente',
      'Cinturão de campeão incluso',
      'Pose de luta dinâmica',
    ],
    specs: [
      { label: 'Material', value: 'Resina Premium Tough' },
      { label: 'Dimensões', value: '20cm x 15cm x 12cm' },
      { label: 'Escala', value: '1:8' },
      { label: 'Tempo de Impressão', value: '16 Horas' },
    ],
    stock: 7,
    rating: 4,
    reviews: 9,
    badges: ['Classic'],
    height: '20cm',
  },
  {
    slug: 'blastoise',
    name: 'Blastoise',
    price: 110,
    oldPrice: 130,
    color: '#00ff00',
    category: 'Classic',
    img: 'https://images.unsplash.com/photo-1566576721346-d4a3b4eaad5b?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1566576721346-d4a3b4eaad5b?q=80&w=600',
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=600',
    ],
    description: 'O starter definitivo da Geração 1. Canhões de água detalhados saindo da carapaça em resina ultra-resistente.',
    details: [
      'Canhões impressos em resina resistente',
      'Carapaça com textura de escama',
      'Base aquática inclusa',
    ],
    specs: [
      { label: 'Material', value: 'Resina ABS-Like' },
      { label: 'Dimensões', value: '22cm x 18cm x 15cm' },
      { label: 'Escala', value: '1:7' },
      { label: 'Tempo de Impressão', value: '19 Horas' },
    ],
    stock: 6,
    rating: 5,
    reviews: 21,
    badges: ['Classic', 'Starter'],
    height: '22cm',
  },
  {
    slug: 'venusaur',
    name: 'Venusaur',
    price: 110,
    color: '#00f3ff',
    category: 'Classic',
    img: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=600',
    ],
    description: 'A flor gigante nas costas em detalhes minuciosos. O starter grama em sua forma final impressa em resina 8K.',
    details: [
      'Pétalas da flor com filamentos visíveis',
      'Textura de pele de sapo na resina',
      'Base de terra inclusa',
    ],
    specs: [
      { label: 'Material', value: 'Resina Premium Tough' },
      { label: 'Dimensões', value: '24cm x 20cm x 18cm' },
      { label: 'Escala', value: '1:7' },
      { label: 'Tempo de Impressão', value: '22 Horas' },
    ],
    stock: 4,
    rating: 4,
    reviews: 14,
    badges: ['Classic', 'Starter'],
    height: '24cm',
  },
  {
    slug: 'lapras',
    name: 'Lapras',
    price: 90,
    color: '#ff00ff',
    category: 'Shiny',
    img: 'https://images.unsplash.com/photo-1544273677-c433136021d4?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1544273677-c433136021d4?q=80&w=600',
    ],
    description: 'Versão Shiny do Lapras em cor rosa metálico. Edição especial com acabamento perolado exclusivo.',
    details: [
      'Acabamento perolado exclusivo versão Shiny',
      'Base de oceano inclusa',
      'Chifre em resina translúcida',
    ],
    specs: [
      { label: 'Material', value: 'Resina Perolada' },
      { label: 'Dimensões', value: '28cm x 15cm x 12cm' },
      { label: 'Escala', value: '1:7' },
      { label: 'Tempo de Impressão', value: '20 Horas' },
    ],
    stock: 3,
    rating: 5,
    reviews: 7,
    badges: ['Shiny', 'Edição Especial'],
    height: '28cm',
  },
  {
    slug: 'arcanine',
    name: 'Arcanine',
    price: 75,
    color: '#00ff00',
    category: 'Classic',
    img: 'https://images.unsplash.com/photo-1606103836293-0a063ee20566?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1606103836293-0a063ee20566?q=80&w=600',
    ],
    description: 'O cão lendário em pose majestosa. Pelos individuais impressos em resolução 8K — impressionante de perto.',
    details: [
      'Pelos individuais em resolução extrema',
      'Chamas das patas em resina translúcida laranja',
      'Base de chama inclusa',
    ],
    specs: [
      { label: 'Material', value: 'Resina Premium Tough' },
      { label: 'Dimensões', value: '25cm x 20cm x 16cm' },
      { label: 'Escala', value: '1:7' },
      { label: 'Tempo de Impressão', value: '18 Horas' },
    ],
    stock: 9,
    rating: 5,
    reviews: 16,
    badges: ['Classic'],
    height: '25cm',
  },
  {
    slug: 'dragonite',
    name: 'Dragonite',
    price: 120,
    oldPrice: 140,
    color: '#00f3ff',
    category: 'Legendary',
    img: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1593305841991-05c297ba4575?q=80&w=600',
    ],
    description: 'O pseudo-lendário em pose de voo. Asas translúcidas com veias visíveis impressas em resina especial.',
    details: [
      'Asas em resina translúcida com veias',
      'Pose de voo com base flutuante',
      'Antenas em resina flexível',
    ],
    specs: [
      { label: 'Material', value: 'Resina Translúcida + Tough' },
      { label: 'Dimensões', value: '32cm x 28cm x 20cm' },
      { label: 'Escala', value: '1:6' },
      { label: 'Tempo de Impressão', value: '26 Horas' },
    ],
    stock: 4,
    rating: 5,
    reviews: 13,
    badges: ['Legendary'],
    height: '32cm',
  },
  {
    slug: 'mewtwo',
    name: 'Mewtwo',
    price: 150,
    oldPrice: 180,
    color: '#ff00ff',
    category: 'Legendary',
    img: 'https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1589254065878-42c9da997008?q=80&w=600',
      'https://images.unsplash.com/photo-1559124568-d5a0f7da1ec5?q=80&w=600',
    ],
    description: 'O lendário genético em pose de poder psíquico. Aura de energia em resina translúcida roxa ao redor do corpo.',
    details: [
      'Aura psíquica em resina translúcida',
      'Olhos com efeito brilhante',
      'Base de laboratório inclusa',
      'Cauda articulada',
    ],
    specs: [
      { label: 'Material', value: 'Resina Premium + Translúcida' },
      { label: 'Dimensões', value: '28cm x 18cm x 14cm' },
      { label: 'Escala', value: '1:7' },
      { label: 'Tempo de Impressão', value: '24 Horas' },
    ],
    stock: 3,
    rating: 5,
    reviews: 41,
    badges: ['Legendary', 'Top Seller'],
    height: '28cm',
  },
  {
    slug: 'articuno',
    name: 'Articuno',
    price: 140,
    color: '#00ff00',
    category: 'Legendary',
    img: 'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1509248961158-e54f6934749c?q=80&w=600',
    ],
    description: 'O pássaro de gelo lendário com asas de cristal. Detalhes de gelo e neve impressos em resina azul translúcida.',
    details: [
      'Asas em resina azul translúcida',
      'Cristais de gelo na base',
      'Cauda em três peças separadas',
    ],
    specs: [
      { label: 'Material', value: 'Resina Translúcida Azul' },
      { label: 'Dimensões', value: '38cm x 30cm x 20cm' },
      { label: 'Escala', value: '1:5' },
      { label: 'Tempo de Impressão', value: '32 Horas' },
    ],
    stock: 2,
    rating: 5,
    reviews: 8,
    badges: ['Legendary', 'Grande Porte'],
    height: '38cm',
  },
  {
    slug: 'charizard',
    name: 'Charizard',
    price: 180,
    oldPrice: 220,
    color: '#00f3ff',
    category: 'Limited',
    img: 'https://images.unsplash.com/photo-1613771404721-1f92d799e49f?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1613771404721-1f92d799e49f?q=80&w=600',
      'https://images.unsplash.com/photo-1594736223565-3544c039a36d?q=80&w=600',
    ],
    description: 'Edição Limitada do dragão de fogo mais famoso. Chamas em resina laranja translúcida com base de vulcão.',
    details: [
      'Edição Limitada — apenas 20 unidades',
      'Chamas em resina translúcida laranja',
      'Base de vulcão inclusa',
      'Asas com nervuras detalhadas',
      'Certificado de autenticidade',
    ],
    specs: [
      { label: 'Material', value: 'Resina Premium + Translúcida' },
      { label: 'Dimensões', value: '30cm x 25cm x 22cm' },
      { label: 'Escala', value: '1:6' },
      { label: 'Tempo de Impressão', value: '28 Horas' },
    ],
    stock: 6,
    rating: 5,
    reviews: 53,
    badges: ['Limited', 'Certificado'],
    height: '30cm',
  },
  {
    slug: 'mew',
    name: 'Mew',
    price: 200,
    color: '#ff00ff',
    category: 'Shiny',
    img: 'https://images.unsplash.com/photo-1559124568-d5a0f7da1ec5?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1559124568-d5a0f7da1ec5?q=80&w=600',
    ],
    description: 'Versão Shiny do Pokémon original. Resina azul metálico com efeito holográfico exclusivo da Balu 3D.',
    details: [
      'Acabamento holográfico exclusivo',
      'Cauda em resina flexível',
      'Base flutuante com suporte transparente',
      'Numerado e assinado',
    ],
    specs: [
      { label: 'Material', value: 'Resina Holográfica' },
      { label: 'Dimensões', value: '14cm x 12cm x 10cm' },
      { label: 'Escala', value: '1:6' },
      { label: 'Tempo de Impressão', value: '12 Horas' },
    ],
    stock: 1,
    rating: 5,
    reviews: 22,
    badges: ['Shiny', 'Numerado', 'Raro'],
    height: '14cm',
  },
  {
    slug: 'eevee',
    name: 'Eevee',
    price: 55,
    color: '#00ff00',
    category: 'Classic',
    img: 'https://images.unsplash.com/photo-1542751110-97427bbecf20?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1542751110-97427bbecf20?q=80&w=600',
    ],
    description: 'O Pokémon mais fofo da lista com pelos detalhados. Gola e rabo com textura de pelo macio impressa em resina.',
    details: [
      'Pelos da gola em resolução máxima',
      'Rabo com 3 peças separadas',
      'Olhos com detalhe reflexivo',
    ],
    specs: [
      { label: 'Material', value: 'Resina Premium Tough' },
      { label: 'Dimensões', value: '10cm x 8cm x 7cm' },
      { label: 'Escala', value: '1:8' },
      { label: 'Tempo de Impressão', value: '7 Horas' },
    ],
    stock: 20,
    rating: 5,
    reviews: 38,
    badges: ['Classic', 'Best Seller'],
    height: '10cm',
  },
  {
    slug: 'snorlax',
    name: 'Snorlax',
    price: 130,
    color: '#00f3ff',
    category: 'Shiny',
    img: 'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=600',
    images: [
      'https://images.unsplash.com/photo-1596461404969-9ae70f2830c1?q=80&w=600',
    ],
    description: 'Versão Shiny verde do Snorlax dormindo. Perfeito para decoração — ocupa espaço com estilo.',
    details: [
      'Versão Shiny cor verde exclusiva',
      'Pose deitado dormindo',
      'Barriga com textura arredondada',
      'Base de grama inclusa',
    ],
    specs: [
      { label: 'Material', value: 'Resina ABS-Like' },
      { label: 'Dimensões', value: '20cm x 15cm x 12cm' },
      { label: 'Escala', value: '1:7' },
      { label: 'Tempo de Impressão', value: '18 Horas' },
    ],
    stock: 5,
    rating: 4,
    reviews: 12,
    badges: ['Shiny'],
    height: '20cm',
  },
]

export function getProductBySlug(slug: string): Product | undefined {
  return catalog.find((p) => p.slug === slug)
}

export const categories = ['Todos', 'Classic', 'Legendary', 'Shiny', 'Limited'] as const
